# Generated by Django 5.2.7 on 2025-10-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
                ('qtd', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
    ]
