# Generated by Django 5.2.7 on 2025-10-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
